# Generated by Django 3.2.6 on 2021-08-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.IntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Transgender'), (3, 'Prefer Not To Say')])),
                ('age', models.IntegerField()),
                ('disease', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=50)),
                ('fees', models.IntegerField(default=500)),
                ('medicationdate', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
