# Generated by Django 3.2.6 on 2021-08-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0002_auto_20210805_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='prof_img',
            field=models.ImageField(default=1, upload_to='profileimg'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(max_length=60),
        ),
    ]
