# Generated by Django 3.2.6 on 2021-08-05 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0003_auto_20210805_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='prof_img',
        ),
    ]
