# Generated by Django 3.2.6 on 2021-08-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0004_remove_patient_prof_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='profile_img',
            field=models.ImageField(default='profile_image.jpg', upload_to='static/images/profileimg'),
        ),
    ]
